### ISSUE TITLE
跑起来了，但是怎么能登录呢

### ISSUE THREAD

**Issue by NashAnd** [miniLV/MNWeibo#11]
点击登录按钮一直跳转失败
![Simulator Screen Shot - iPhone 8 - 2022-01-06 at 09 55 12](https://user-images.githubusercontent.com/14804016/148315591-09b80641-5c8d-4537-93f8-fe4a1707cc20.png)

**Comment by miniLV** [comment]
这个是weiboSDK的问题，https://github.com/sinaweibosdk/weibo_ios_sdk/blob/master/FAQ.md 这里有一些常见的问题解答

如果只是想试验功能的话，可以pull 一下最新的代码，#16 提供了mock的功能了
