### ISSUE TITLE
请问有大佬碰到过M1芯片适配问题么？求指点

### ISSUE THREAD

**Issue by Jasonhunger** [miniLV/MNWeibo#13]
<img width="708" alt="image" src="https://user-images.githubusercontent.com/45938197/225032219-cc53f8da-6909-417c-a932-4c8116133627.png">

**Comment by miniLV** [comment]
这个是weiboSDK的问题，描述上看他不支持iOS 模拟器架构，可以用真机试试

或者可以选择 `Designed for iPad` 运行试试
