### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by NingTong** [miniLV/MNWeibo#3]
首先，点击登录后，会拉起网页登录，然后会再跳转到新的登录页，在新的登录页登录成功后，进入的是网页版微博；
其次，点网页关闭按钮，会返回博主想要的老登录页，但是这个登录页无法登录。
app无法登录，很多功能都看不了，只能光看代码了，希望可以解决下

**Comment by miniLV** [comment]
不好意思，最近比较忙没注意看消息，此bug已修复，请再试试.
