### ISSUE TITLE
导航有考虑怎么处理吗。如果在VC跳转，感觉好像不太好

### ISSUE THREAD

**Issue by soulne** [miniLV/MNWeibo#5]

**Comment by zhllm** [comment]
userInfo.json 你的项目里有吗？

**Comment by miniLV** [comment]
@zhllm 你好，你需要登录成功一次，必须拿到用户信息才能进行本地保存，所以请先登录成功一次，如果还有问题，可以新开一个issue

**Comment by miniLV** [comment]
@soulne 你好，关于导航条跳转的需求可以详细说明一下吗

**Comment by miniLV** [comment]
由于没有后续，关闭这个issue, 如果还有问题请再开一个，3Q
